version: "3"
services:
  app:
    build: .
    image: lwymetal/ibay_sbc:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "80:3000"
    environment:
      MYSQL_DATABASE: rates
      MYSQL_USER: root
    depends_on:
      - db
  db:
    image: mysql:5.7
    volumes: 
      - rates:/var/lib/mysql
  networks: 
    - connector
volumes:
  rates:
networks:
  connector:
    driver: bridge

